p_total_r_nh_upper <- vector(mode = "numeric", length=58)
p_total_r_nh <- vector(mode = "numeric", length=58)
p_total_r_nh_lower <- vector(mode = "numeric", length=58)
p_g_1_r_nh_upper <- vector(mode = "numeric", length=58)
p_g_1_r_nh <- vector(mode = "numeric", length=58)
p_g_1_r_nh_lower <- vector(mode = "numeric", length=58)
p_g_2_r_nh_upper <- vector(mode = "numeric", length=58)
p_g_2_r_nh <- vector(mode = "numeric", length=58)
p_g_2_r_nh_lower <- vector(mode = "numeric", length=58)
for (i in 1:58) {
  p_total_r_nh_upper[i] <- quantile(total_r_nh[seq(i, 578+i, by=58)], 0.8)
  p_total_r_nh[i] <- mean(total_r_nh[seq(i, 578+i, by=58)])
  p_total_r_nh_lower[i] <- quantile(total_r_nh[seq(i, 578+i, by=58)], 0.2)
  p_g_1_r_nh_upper[i] <- quantile(g_1_r_nh[seq(i, 578+i, by=58)], 0.8)
  p_g_1_r_nh[i] <- mean(g_1_r_nh[seq(i, 578+i, by=58)])
  p_g_1_r_nh_lower[i] <- quantile(g_1_r_nh[seq(i, 578+i, by=58)], 0.2)
  p_g_2_r_nh_upper[i] <- quantile(g_2_r_nh[seq(i, 578+i, by=58)], 0.8)
  p_g_2_r_nh[i] <- mean(g_2_r_nh[seq(i, 578+i, by=58)])
  p_g_2_r_nh_lower[i] <- quantile(g_2_r_nh[seq(i, 578+i, by=58)], 0.2)
}

p_total_r_h_upper <- vector(mode = "numeric", length=58)
p_total_r_h <- vector(mode = "numeric", length=58)
p_total_r_h_lower <- vector(mode = "numeric", length=58)
p_g_1_r_h_upper <- vector(mode = "numeric", length=58)
p_g_1_r_h <- vector(mode = "numeric", length=58)
p_g_1_r_h_lower <- vector(mode = "numeric", length=58)
p_g_2_r_h_upper <- vector(mode = "numeric", length=58)
p_g_2_r_h <- vector(mode = "numeric", length=58)
p_g_2_r_h_lower <- vector(mode = "numeric", length=58)
for (i in 1:58) {
  p_total_r_h_upper[i] <- quantile(total_r_h[seq(i, 578+i, by=58)], 0.8)
  p_total_r_h[i] <- mean(total_r_h[seq(i, 578+i, by=58)])
  p_total_r_h_lower[i] <- quantile(total_r_h[seq(i, 578+i, by=58)], 0.2)
  p_g_1_r_h_upper[i] <- quantile(g_1_r_h[seq(i, 578+i, by=58)], 0.8)
  p_g_1_r_h[i] <- mean(g_1_r_h[seq(i, 578+i, by=58)])
  p_g_1_r_h_lower[i] <- quantile(g_1_r_h[seq(i, 578+i, by=58)], 0.2)
  p_g_2_r_h_upper[i] <- quantile(g_2_r_h[seq(i, 578+i, by=58)], 0.8)
  p_g_2_r_h[i] <- mean(g_2_r_h[seq(i, 578+i, by=58)])
  p_g_2_r_h_lower[i] <- quantile(g_2_r_h[seq(i, 578+i, by=58)], 0.2)
}



plot(p_total_r_nh, ylab="Abundance",xlab="Time (units of 3 month intervals)", ylim=c(0,max(p_total_r_nh_upper)), main= "No harvesting, variable resource", type="l", lty=1)
lines(p_total_r_nh_upper, type="l", lty=1, lwd=0.3)
lines(p_total_r_nh_lower, type="l", lty=1, lwd=0.3)
lines(p_g_1_r_nh, type="l", lty=2, col="blue")
lines(p_g_1_r_nh_upper, type="l", lty=2, lwd=0.3, col="blue")
lines(p_g_1_r_nh_lower, type="l", lty=2, lwd=0.3, col="blue")
lines(p_g_2_r_nh, type="l", lty=3, col="red")
lines(p_g_2_r_nh_upper, type="l", lty=3, lwd=0.3, col="red")
lines(p_g_2_r_nh_lower, type="l", lty=3, lwd=0.3, col="red")


plot(p_total_r_h, ylab="Abundance",xlab="Time (units of 3 month intervals)", ylim=c(0,max(p_total_r_h_upper)), main= "Harvesting, variable resource", type="l", lty=1)
lines(p_total_r_h_upper, type="l", lty=1, lwd=0.3)
lines(p_total_r_h_lower, type="l", lty=1, lwd=0.3)

lines(p_g_1_r_h, type="l", lty=2, col="blue")
lines(p_g_1_r_h_upper, type="l", lty=2, lwd=0.3, col="blue")
lines(p_g_1_r_h_lower, type="l", lty=2, lwd=0.3, col="blue")
lines(p_g_2_r_h, type="l", lty=3, col="red")
lines(p_g_2_r_h_upper, type="l", lty=3, lwd=0.3, col="red")
lines(p_g_2_r_h_lower, type="l", lty=3, lwd=0.3, col="red")
legend("topright",legend=c("all", "large maturer","small maturer"), lty=1:3, col=c("black","blue","red"))
